version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql-network

  mysql-workbench:
    image: mysql/mysql-workbench:latest
    container_name: mysql_workbench
    depends_on:
      - mysql
    networks:
      - mysql-network
    ports:
      - "3000:3000"  # Expose this port for the Workbench
    volumes:
      - ./dockerize:/usr/local/bin/dockerize  # Mount dockerize binary
    entrypoint: >
      dockerize -wait tcp://mysql:3306 -timeout 30s
      && /usr/local/bin/start-mysql-workbench  # Replace with the actual workbench start command
    stdin_open: true
    tty: true

networks:
  mysql-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
